### ISSUE TITLE
[Bug] SWADE: GM can't give a Benny to Players

### ISSUE THREAD

**Issue by Vogliadicone** [mclemente/fvtt-module-permission-viewer#1]
After updating to Ownership Viewer 11.0 I can't give my players Bennies (as a GM).

Without Ownership Viewer I get a "+" when I hover over my players Bennies in the player list:
![Benny_2](https://github.com/mclemente/fvtt-module-permission-viewer/assets/119852651/0e465bcb-6c3b-482d-9a73-6ea4563e6ce4)
And by clicking on that the player get's a new benny.

With Ownership Viewer I still get the tool tip, but I don't see the "+" and clicking on the number doesn't change the number of Bennies of the player:
![Benny_1](https://github.com/mclemente/fvtt-module-permission-viewer/assets/119852651/9d9c55ba-5f0e-4ff2-a08d-0d9bb8918799)

I could reproduce the problem in 2 worlds without any other modules beside Ownership Viewer.

Let me know, if you need more information.

- Foundry VTT: 11.304 (on Oracle Cloud)
- Ownership Viewer: 11.0
- Swade System: 3.0.4
- Browser: Google Chrome

**Comment by mclemente** [comment]
Should be fixed on the latest version now.
