### ISSUE TITLE
Error reported when opening Journal

### ISSUE THREAD

**Issue by farling42** [mclemente/fvtt-module-permission-viewer#16]
**Describe the bug**
Error reported in console when opening a journal

**To Reproduce**
1. Open a journal
2. See an error similar to the screenshot in the browser console

**Expected behavior**
No error, and ownership should be displayed in the journal page.

**Screenshots**
![image](https://github.com/user-attachments/assets/a0349feb-13cd-4b9d-9736-94cddfe6ad3e)

**Foundry Information & Browser (please complete the following information):**
 - Foundry version 12.331
 - Permission Viewer Version 12.3
 - Game System: PF2E 6.6.1
 - Browser Chrome 130.0.6723.92

**Additional context**

**Comment by farling42** [comment]
Perhaps caused by querySelector() returning null, whereas find() returns an empty array (and thus no error is generated from find).

**Comment by CaosFR** [comment]
Same for me, +1
