### ISSUE TITLE
PV Bug Report - Performance Problems when activated

### ISSUE THREAD

**Issue by BokuNC** [mclemente/fvtt-module-permission-viewer#9]
**Describe the bug**
In a direct way, having this module activated as it is, in the last version, makes foundry run extremely slower for Game Masters (Which i assume would be true also if other permissions were given to other player levels). Tested with just the bare world and this module and it takes minutes to open a scene and each journal i try to open for the first time freezes the browser tab for foundry for a while. 

**To Reproduce**
1. Go to any worlds with some amount of Journals and Actors;
2. Click on activate or deactivate the module;
3. Take note from the time it takes to run and open anything;

**Expected behavior**
I haven't noticed this before and i've been using Ownership Viewer since i started using Foundry. Being a module that only makes a already existing configuration visible easily for organization purposes, i expect it to not affect the performance of my worlds.

**Foundry Information & Browser (please complete the following information):**
 - Foundry version: Last Stable V11 Version;
 - Permission Viewer Version: v11.7;
 - Browser: Any browser that i tried, so Firefox, Chrome and Edge;

**Comment by mclemente** [comment]
This should be fixed with https://github.com/mclemente/fvtt-module-permission-viewer/pull/15. I hope this solves the issue for you, if it isn't, feel free to report it again.

I couldn't replicate this issue myself because I assumed "bare world" meant a new world with just a few actors, which didn't slow down the game for me as it was reported.

**Comment by BokuNC** [comment]
When referring to "Bare world" i tried to say no other modules activated. But don't seem to be having this problem anymore, so yeah, probably solved.
